# permissions for end users to view initiatorgroupbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: initiatorgroupbinding-viewer-role
rules:
- apiGroups:
  - tgtd.unstable.cloud
  resources:
  - initiatorgroupbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tgtd.unstable.cloud
  resources:
  - initiatorgroupbindings/status
  verbs:
  - get
