# permissions for end users to edit initiatorgroupbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: initiatorgroupbinding-editor-role
rules:
- apiGroups:
  - tgtd.unstable.cloud
  resources:
  - initiatorgroupbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tgtd.unstable.cloud
  resources:
  - initiatorgroupbindings/status
  verbs:
  - get
