apiVersion: tgtd.unstable.cloud/v1alpha1
kind: InitiatorGroupBinding
metadata:
  name: initiatorgroupbinding-sample
spec:
  targetRef:
    name: target-sample
  initiatorGroupRef:
    name: initiatorgroup-sample
